---
title: "126 HW2"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
#3.3.1

library(alr4)
BGSgirls
data1 <- BGSgirls[,c(2,4,1,3,6,11)]
data1
pairs(HT2~HT9+WT2+WT9+ST9+BMI18, data = data1)
cor(data1)

# the correlation between the variables HT2, HT9, WT2, WT9, ST9 and BMI18 shows that
#they have a positive correlation


#3.3.2
fit1<-lm(BMI18~WT9,data=BGSgirls)
summary(fit1)

fit2<-lm(BMI18~ST9,data=BGSgirls)
summary(fit2)

fit3<-lm(ST9~WT9, data=BGSgirls)
summary(fit2)

fit4<-lm(fit1$residuals~fit3$residuals)
summary(fit4)

par(mfrow=c(1,2))
plot(fit3$residuals,fit1$residuals,
     main="Add-variable plot")
abline(fit4,col="red")

#The added variable plot is of the unexplained part of the response BMI18 from fit1 
#residuals on the unexplained part of the added regressor from fit3 residuals. 
#It summarizes the relationship between BMI18 and ST9 adjusting for WT9.

#3.3.3
model=lm(BMI18~HT2+HT9+WT9+ST9,data=water)
summary(model)

#The value of sigma hat and R-square are 2.14 and 0.4431



#3.6.1

attach(water)
pairs(BSAAM~OPBPC+OPRC+OPSLAKE,data=water)
data=cbind(BSAAM,OPBPC,OPRC,OPSLAKE)
cor(data)
#The correlation values will be large and positive for all the variables
#for each variable, correlation value is approximately equal to one
#OPSLAkE and OPBPC have the highewt correlation

#3.6.2

summary(lm(BSAAM~OPBPC+OPRC+OPSLAKE))

#The t-value with corresponding p-value will give the evidence against the null hypothesis.
#that's whether there is enough evidence to say the parameter coefficients are most likely nonzero



```
```

## Including Plots

You can also embed plots, for example:

```{r pressure}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
